// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/fenek-dev/go-twitter/src/common/models"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateTweet provides a mock function with given fields: ctx, username, content
func (_m *Service) CreateTweet(ctx context.Context, username string, content string) (*models.Tweet, error) {
	ret := _m.Called(ctx, username, content)

	if len(ret) == 0 {
		panic("no return value specified for CreateTweet")
	}

	var r0 *models.Tweet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Tweet, error)); ok {
		return rf(ctx, username, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Tweet); ok {
		r0 = rf(ctx, username, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Tweet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTweet provides a mock function with given fields: ctx, id
func (_m *Service) DeleteTweet(ctx context.Context, id string) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTweet")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTweetById provides a mock function with given fields: ctx, id
func (_m *Service) FindTweetById(ctx context.Context, id string) (*models.Tweet, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindTweetById")
	}

	var r0 *models.Tweet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Tweet, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Tweet); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Tweet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTweet provides a mock function with given fields: ctx, id, content
func (_m *Service) UpdateTweet(ctx context.Context, id string, content string) (*models.Tweet, error) {
	ret := _m.Called(ctx, id, content)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTweet")
	}

	var r0 *models.Tweet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Tweet, error)); ok {
		return rf(ctx, id, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Tweet); ok {
		r0 = rf(ctx, id, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Tweet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
