// Code generated by mockery v2.43.2. DO NOT EDIT.

package proto_mocks

import (
	context "context"

	ssov1 "github.com/fenek-dev/go-twitter/proto/protogen"
	mock "github.com/stretchr/testify/mock"
)

// AuthServiceServer is an autogenerated mock type for the AuthServiceServer type
type AuthServiceServer struct {
	mock.Mock
}

// Login provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) Login(_a0 context.Context, _a1 *ssov1.LoginRequest) (*ssov1.LoginResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *ssov1.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.LoginRequest) (*ssov1.LoginResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.LoginRequest) *ssov1.LoginResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.LoginRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) Register(_a0 context.Context, _a1 *ssov1.RegisterRequest) (*ssov1.RegisterResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *ssov1.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.RegisterRequest) (*ssov1.RegisterResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.RegisterRequest) *ssov1.RegisterResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.RegisterRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Verify provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) Verify(_a0 context.Context, _a1 *ssov1.VerifyRequest) (*ssov1.VerifyResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *ssov1.VerifyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.VerifyRequest) (*ssov1.VerifyResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.VerifyRequest) *ssov1.VerifyResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.VerifyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.VerifyRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedAuthServiceServer provides a mock function with given fields:
func (_m *AuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {
	_m.Called()
}

// NewAuthServiceServer creates a new instance of AuthServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceServer {
	mock := &AuthServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
