// Code generated by mockery v2.43.2. DO NOT EDIT.

package proto_mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	ssov1 "github.com/fenek-dev/go-twitter/proto/protogen"
)

// AuthServiceClient is an autogenerated mock type for the AuthServiceClient type
type AuthServiceClient struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *AuthServiceClient) Login(ctx context.Context, in *ssov1.LoginRequest, opts ...grpc.CallOption) (*ssov1.LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *ssov1.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.LoginRequest, ...grpc.CallOption) (*ssov1.LoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.LoginRequest, ...grpc.CallOption) *ssov1.LoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, in, opts
func (_m *AuthServiceClient) Register(ctx context.Context, in *ssov1.RegisterRequest, opts ...grpc.CallOption) (*ssov1.RegisterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *ssov1.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.RegisterRequest, ...grpc.CallOption) (*ssov1.RegisterResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.RegisterRequest, ...grpc.CallOption) *ssov1.RegisterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.RegisterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Verify provides a mock function with given fields: ctx, in, opts
func (_m *AuthServiceClient) Verify(ctx context.Context, in *ssov1.VerifyRequest, opts ...grpc.CallOption) (*ssov1.VerifyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *ssov1.VerifyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.VerifyRequest, ...grpc.CallOption) (*ssov1.VerifyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.VerifyRequest, ...grpc.CallOption) *ssov1.VerifyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.VerifyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.VerifyRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthServiceClient creates a new instance of AuthServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceClient {
	mock := &AuthServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
