// Code generated by mockery v2.43.2. DO NOT EDIT.

package proto_mocks

import (
	context "context"

	ssov1 "github.com/fenek-dev/go-twitter/proto/protogen"
	mock "github.com/stretchr/testify/mock"
)

// CacheServiceServer is an autogenerated mock type for the CacheServiceServer type
type CacheServiceServer struct {
	mock.Mock
}

// CreateTweet provides a mock function with given fields: _a0, _a1
func (_m *CacheServiceServer) CreateTweet(_a0 context.Context, _a1 *ssov1.CreateTweetRequest) (*ssov1.CreateTweetResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateTweet")
	}

	var r0 *ssov1.CreateTweetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.CreateTweetRequest) (*ssov1.CreateTweetResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.CreateTweetRequest) *ssov1.CreateTweetResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.CreateTweetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.CreateTweetRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTweet provides a mock function with given fields: _a0, _a1
func (_m *CacheServiceServer) DeleteTweet(_a0 context.Context, _a1 *ssov1.DeleteTweetRequest) (*ssov1.DeleteTweetResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTweet")
	}

	var r0 *ssov1.DeleteTweetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.DeleteTweetRequest) (*ssov1.DeleteTweetResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.DeleteTweetRequest) *ssov1.DeleteTweetResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.DeleteTweetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.DeleteTweetRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTweetById provides a mock function with given fields: _a0, _a1
func (_m *CacheServiceServer) FindTweetById(_a0 context.Context, _a1 *ssov1.FindTweetByIdRequest) (*ssov1.FindTweetByIdResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FindTweetById")
	}

	var r0 *ssov1.FindTweetByIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.FindTweetByIdRequest) (*ssov1.FindTweetByIdResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.FindTweetByIdRequest) *ssov1.FindTweetByIdResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.FindTweetByIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.FindTweetByIdRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserById provides a mock function with given fields: _a0, _a1
func (_m *CacheServiceServer) FindUserById(_a0 context.Context, _a1 *ssov1.FindUserByIdRequest) (*ssov1.FindUserByIdResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FindUserById")
	}

	var r0 *ssov1.FindUserByIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.FindUserByIdRequest) (*ssov1.FindUserByIdResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.FindUserByIdRequest) *ssov1.FindUserByIdResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.FindUserByIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.FindUserByIdRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveUser provides a mock function with given fields: _a0, _a1
func (_m *CacheServiceServer) SaveUser(_a0 context.Context, _a1 *ssov1.SaveUserRequest) (*ssov1.SaveUserResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 *ssov1.SaveUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.SaveUserRequest) (*ssov1.SaveUserResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.SaveUserRequest) *ssov1.SaveUserResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.SaveUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.SaveUserRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTweet provides a mock function with given fields: _a0, _a1
func (_m *CacheServiceServer) UpdateTweet(_a0 context.Context, _a1 *ssov1.UpdateTweetRequest) (*ssov1.UpdateTweetResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTweet")
	}

	var r0 *ssov1.UpdateTweetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.UpdateTweetRequest) (*ssov1.UpdateTweetResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.UpdateTweetRequest) *ssov1.UpdateTweetResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.UpdateTweetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.UpdateTweetRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedCacheServiceServer provides a mock function with given fields:
func (_m *CacheServiceServer) mustEmbedUnimplementedCacheServiceServer() {
	_m.Called()
}

// NewCacheServiceServer creates a new instance of CacheServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheServiceServer {
	mock := &CacheServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
