// Code generated by mockery v2.43.2. DO NOT EDIT.

package proto_mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	ssov1 "github.com/fenek-dev/go-twitter/proto/protogen"
)

// CacheServiceClient is an autogenerated mock type for the CacheServiceClient type
type CacheServiceClient struct {
	mock.Mock
}

// CreateTweet provides a mock function with given fields: ctx, in, opts
func (_m *CacheServiceClient) CreateTweet(ctx context.Context, in *ssov1.CreateTweetRequest, opts ...grpc.CallOption) (*ssov1.CreateTweetResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateTweet")
	}

	var r0 *ssov1.CreateTweetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.CreateTweetRequest, ...grpc.CallOption) (*ssov1.CreateTweetResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.CreateTweetRequest, ...grpc.CallOption) *ssov1.CreateTweetResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.CreateTweetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.CreateTweetRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTweet provides a mock function with given fields: ctx, in, opts
func (_m *CacheServiceClient) DeleteTweet(ctx context.Context, in *ssov1.DeleteTweetRequest, opts ...grpc.CallOption) (*ssov1.DeleteTweetResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTweet")
	}

	var r0 *ssov1.DeleteTweetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.DeleteTweetRequest, ...grpc.CallOption) (*ssov1.DeleteTweetResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.DeleteTweetRequest, ...grpc.CallOption) *ssov1.DeleteTweetResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.DeleteTweetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.DeleteTweetRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTweetById provides a mock function with given fields: ctx, in, opts
func (_m *CacheServiceClient) FindTweetById(ctx context.Context, in *ssov1.FindTweetByIdRequest, opts ...grpc.CallOption) (*ssov1.FindTweetByIdResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindTweetById")
	}

	var r0 *ssov1.FindTweetByIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.FindTweetByIdRequest, ...grpc.CallOption) (*ssov1.FindTweetByIdResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.FindTweetByIdRequest, ...grpc.CallOption) *ssov1.FindTweetByIdResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.FindTweetByIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.FindTweetByIdRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserById provides a mock function with given fields: ctx, in, opts
func (_m *CacheServiceClient) FindUserById(ctx context.Context, in *ssov1.FindUserByIdRequest, opts ...grpc.CallOption) (*ssov1.FindUserByIdResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindUserById")
	}

	var r0 *ssov1.FindUserByIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.FindUserByIdRequest, ...grpc.CallOption) (*ssov1.FindUserByIdResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.FindUserByIdRequest, ...grpc.CallOption) *ssov1.FindUserByIdResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.FindUserByIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.FindUserByIdRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveUser provides a mock function with given fields: ctx, in, opts
func (_m *CacheServiceClient) SaveUser(ctx context.Context, in *ssov1.SaveUserRequest, opts ...grpc.CallOption) (*ssov1.SaveUserResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 *ssov1.SaveUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.SaveUserRequest, ...grpc.CallOption) (*ssov1.SaveUserResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.SaveUserRequest, ...grpc.CallOption) *ssov1.SaveUserResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.SaveUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.SaveUserRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTweet provides a mock function with given fields: ctx, in, opts
func (_m *CacheServiceClient) UpdateTweet(ctx context.Context, in *ssov1.UpdateTweetRequest, opts ...grpc.CallOption) (*ssov1.UpdateTweetResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTweet")
	}

	var r0 *ssov1.UpdateTweetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.UpdateTweetRequest, ...grpc.CallOption) (*ssov1.UpdateTweetResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssov1.UpdateTweetRequest, ...grpc.CallOption) *ssov1.UpdateTweetResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssov1.UpdateTweetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssov1.UpdateTweetRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCacheServiceClient creates a new instance of CacheServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheServiceClient {
	mock := &CacheServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
