// Code generated by MockGen. DO NOT EDIT.
// Source: proto/protogen/twitter_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=proto/protogen/twitter_grpc.pb.go -destination=proto/protogen/mocks/twitter_mock.go
//

// Package mock_ssov1 is a generated GoMock package.
package mock_ssov1

import (
	context "context"
	reflect "reflect"

	protogen "github.com/fenek-dev/go-twitter/proto/protogen"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockAuthServiceClient is a mock of AuthServiceClient interface.
type MockAuthServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceClientMockRecorder
}

// MockAuthServiceClientMockRecorder is the mock recorder for MockAuthServiceClient.
type MockAuthServiceClientMockRecorder struct {
	mock *MockAuthServiceClient
}

// NewMockAuthServiceClient creates a new mock instance.
func NewMockAuthServiceClient(ctrl *gomock.Controller) *MockAuthServiceClient {
	mock := &MockAuthServiceClient{ctrl: ctrl}
	mock.recorder = &MockAuthServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceClient) EXPECT() *MockAuthServiceClientMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthServiceClient) Login(ctx context.Context, in *protogen.LoginRequest, opts ...grpc.CallOption) (*protogen.LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Login", varargs...)
	ret0, _ := ret[0].(*protogen.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceClientMockRecorder) Login(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthServiceClient)(nil).Login), varargs...)
}

// Register mocks base method.
func (m *MockAuthServiceClient) Register(ctx context.Context, in *protogen.RegisterRequest, opts ...grpc.CallOption) (*protogen.RegisterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Register", varargs...)
	ret0, _ := ret[0].(*protogen.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceClientMockRecorder) Register(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthServiceClient)(nil).Register), varargs...)
}

// Verify mocks base method.
func (m *MockAuthServiceClient) Verify(ctx context.Context, in *protogen.VerifyRequest, opts ...grpc.CallOption) (*protogen.VerifyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Verify", varargs...)
	ret0, _ := ret[0].(*protogen.VerifyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockAuthServiceClientMockRecorder) Verify(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockAuthServiceClient)(nil).Verify), varargs...)
}

// MockAuthServiceServer is a mock of AuthServiceServer interface.
type MockAuthServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceServerMockRecorder
}

// MockAuthServiceServerMockRecorder is the mock recorder for MockAuthServiceServer.
type MockAuthServiceServerMockRecorder struct {
	mock *MockAuthServiceServer
}

// NewMockAuthServiceServer creates a new mock instance.
func NewMockAuthServiceServer(ctrl *gomock.Controller) *MockAuthServiceServer {
	mock := &MockAuthServiceServer{ctrl: ctrl}
	mock.recorder = &MockAuthServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceServer) EXPECT() *MockAuthServiceServerMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthServiceServer) Login(arg0 context.Context, arg1 *protogen.LoginRequest) (*protogen.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1)
	ret0, _ := ret[0].(*protogen.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceServerMockRecorder) Login(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthServiceServer)(nil).Login), arg0, arg1)
}

// Register mocks base method.
func (m *MockAuthServiceServer) Register(arg0 context.Context, arg1 *protogen.RegisterRequest) (*protogen.RegisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1)
	ret0, _ := ret[0].(*protogen.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceServerMockRecorder) Register(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthServiceServer)(nil).Register), arg0, arg1)
}

// Verify mocks base method.
func (m *MockAuthServiceServer) Verify(arg0 context.Context, arg1 *protogen.VerifyRequest) (*protogen.VerifyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", arg0, arg1)
	ret0, _ := ret[0].(*protogen.VerifyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockAuthServiceServerMockRecorder) Verify(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockAuthServiceServer)(nil).Verify), arg0, arg1)
}

// mustEmbedUnimplementedAuthServiceServer mocks base method.
func (m *MockAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedAuthServiceServer")
}

// mustEmbedUnimplementedAuthServiceServer indicates an expected call of mustEmbedUnimplementedAuthServiceServer.
func (mr *MockAuthServiceServerMockRecorder) mustEmbedUnimplementedAuthServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedAuthServiceServer", reflect.TypeOf((*MockAuthServiceServer)(nil).mustEmbedUnimplementedAuthServiceServer))
}

// MockUnsafeAuthServiceServer is a mock of UnsafeAuthServiceServer interface.
type MockUnsafeAuthServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeAuthServiceServerMockRecorder
}

// MockUnsafeAuthServiceServerMockRecorder is the mock recorder for MockUnsafeAuthServiceServer.
type MockUnsafeAuthServiceServerMockRecorder struct {
	mock *MockUnsafeAuthServiceServer
}

// NewMockUnsafeAuthServiceServer creates a new mock instance.
func NewMockUnsafeAuthServiceServer(ctrl *gomock.Controller) *MockUnsafeAuthServiceServer {
	mock := &MockUnsafeAuthServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeAuthServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeAuthServiceServer) EXPECT() *MockUnsafeAuthServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedAuthServiceServer mocks base method.
func (m *MockUnsafeAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedAuthServiceServer")
}

// mustEmbedUnimplementedAuthServiceServer indicates an expected call of mustEmbedUnimplementedAuthServiceServer.
func (mr *MockUnsafeAuthServiceServerMockRecorder) mustEmbedUnimplementedAuthServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedAuthServiceServer", reflect.TypeOf((*MockUnsafeAuthServiceServer)(nil).mustEmbedUnimplementedAuthServiceServer))
}

// MockCacheServiceClient is a mock of CacheServiceClient interface.
type MockCacheServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCacheServiceClientMockRecorder
}

// MockCacheServiceClientMockRecorder is the mock recorder for MockCacheServiceClient.
type MockCacheServiceClientMockRecorder struct {
	mock *MockCacheServiceClient
}

// NewMockCacheServiceClient creates a new mock instance.
func NewMockCacheServiceClient(ctrl *gomock.Controller) *MockCacheServiceClient {
	mock := &MockCacheServiceClient{ctrl: ctrl}
	mock.recorder = &MockCacheServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheServiceClient) EXPECT() *MockCacheServiceClientMockRecorder {
	return m.recorder
}

// CreateTweet mocks base method.
func (m *MockCacheServiceClient) CreateTweet(ctx context.Context, in *protogen.CreateTweetRequest, opts ...grpc.CallOption) (*protogen.CreateTweetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTweet", varargs...)
	ret0, _ := ret[0].(*protogen.CreateTweetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTweet indicates an expected call of CreateTweet.
func (mr *MockCacheServiceClientMockRecorder) CreateTweet(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTweet", reflect.TypeOf((*MockCacheServiceClient)(nil).CreateTweet), varargs...)
}

// DeleteTweet mocks base method.
func (m *MockCacheServiceClient) DeleteTweet(ctx context.Context, in *protogen.DeleteTweetRequest, opts ...grpc.CallOption) (*protogen.DeleteTweetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteTweet", varargs...)
	ret0, _ := ret[0].(*protogen.DeleteTweetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTweet indicates an expected call of DeleteTweet.
func (mr *MockCacheServiceClientMockRecorder) DeleteTweet(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTweet", reflect.TypeOf((*MockCacheServiceClient)(nil).DeleteTweet), varargs...)
}

// FindTweetById mocks base method.
func (m *MockCacheServiceClient) FindTweetById(ctx context.Context, in *protogen.FindTweetByIdRequest, opts ...grpc.CallOption) (*protogen.FindTweetByIdResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindTweetById", varargs...)
	ret0, _ := ret[0].(*protogen.FindTweetByIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTweetById indicates an expected call of FindTweetById.
func (mr *MockCacheServiceClientMockRecorder) FindTweetById(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTweetById", reflect.TypeOf((*MockCacheServiceClient)(nil).FindTweetById), varargs...)
}

// FindUserById mocks base method.
func (m *MockCacheServiceClient) FindUserById(ctx context.Context, in *protogen.FindUserByIdRequest, opts ...grpc.CallOption) (*protogen.FindUserByIdResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindUserById", varargs...)
	ret0, _ := ret[0].(*protogen.FindUserByIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserById indicates an expected call of FindUserById.
func (mr *MockCacheServiceClientMockRecorder) FindUserById(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserById", reflect.TypeOf((*MockCacheServiceClient)(nil).FindUserById), varargs...)
}

// SaveUser mocks base method.
func (m *MockCacheServiceClient) SaveUser(ctx context.Context, in *protogen.SaveUserRequest, opts ...grpc.CallOption) (*protogen.SaveUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveUser", varargs...)
	ret0, _ := ret[0].(*protogen.SaveUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockCacheServiceClientMockRecorder) SaveUser(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockCacheServiceClient)(nil).SaveUser), varargs...)
}

// UpdateTweet mocks base method.
func (m *MockCacheServiceClient) UpdateTweet(ctx context.Context, in *protogen.UpdateTweetRequest, opts ...grpc.CallOption) (*protogen.UpdateTweetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateTweet", varargs...)
	ret0, _ := ret[0].(*protogen.UpdateTweetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTweet indicates an expected call of UpdateTweet.
func (mr *MockCacheServiceClientMockRecorder) UpdateTweet(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTweet", reflect.TypeOf((*MockCacheServiceClient)(nil).UpdateTweet), varargs...)
}

// MockCacheServiceServer is a mock of CacheServiceServer interface.
type MockCacheServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockCacheServiceServerMockRecorder
}

// MockCacheServiceServerMockRecorder is the mock recorder for MockCacheServiceServer.
type MockCacheServiceServerMockRecorder struct {
	mock *MockCacheServiceServer
}

// NewMockCacheServiceServer creates a new mock instance.
func NewMockCacheServiceServer(ctrl *gomock.Controller) *MockCacheServiceServer {
	mock := &MockCacheServiceServer{ctrl: ctrl}
	mock.recorder = &MockCacheServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheServiceServer) EXPECT() *MockCacheServiceServerMockRecorder {
	return m.recorder
}

// CreateTweet mocks base method.
func (m *MockCacheServiceServer) CreateTweet(arg0 context.Context, arg1 *protogen.CreateTweetRequest) (*protogen.CreateTweetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTweet", arg0, arg1)
	ret0, _ := ret[0].(*protogen.CreateTweetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTweet indicates an expected call of CreateTweet.
func (mr *MockCacheServiceServerMockRecorder) CreateTweet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTweet", reflect.TypeOf((*MockCacheServiceServer)(nil).CreateTweet), arg0, arg1)
}

// DeleteTweet mocks base method.
func (m *MockCacheServiceServer) DeleteTweet(arg0 context.Context, arg1 *protogen.DeleteTweetRequest) (*protogen.DeleteTweetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTweet", arg0, arg1)
	ret0, _ := ret[0].(*protogen.DeleteTweetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTweet indicates an expected call of DeleteTweet.
func (mr *MockCacheServiceServerMockRecorder) DeleteTweet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTweet", reflect.TypeOf((*MockCacheServiceServer)(nil).DeleteTweet), arg0, arg1)
}

// FindTweetById mocks base method.
func (m *MockCacheServiceServer) FindTweetById(arg0 context.Context, arg1 *protogen.FindTweetByIdRequest) (*protogen.FindTweetByIdResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTweetById", arg0, arg1)
	ret0, _ := ret[0].(*protogen.FindTweetByIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTweetById indicates an expected call of FindTweetById.
func (mr *MockCacheServiceServerMockRecorder) FindTweetById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTweetById", reflect.TypeOf((*MockCacheServiceServer)(nil).FindTweetById), arg0, arg1)
}

// FindUserById mocks base method.
func (m *MockCacheServiceServer) FindUserById(arg0 context.Context, arg1 *protogen.FindUserByIdRequest) (*protogen.FindUserByIdResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserById", arg0, arg1)
	ret0, _ := ret[0].(*protogen.FindUserByIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserById indicates an expected call of FindUserById.
func (mr *MockCacheServiceServerMockRecorder) FindUserById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserById", reflect.TypeOf((*MockCacheServiceServer)(nil).FindUserById), arg0, arg1)
}

// SaveUser mocks base method.
func (m *MockCacheServiceServer) SaveUser(arg0 context.Context, arg1 *protogen.SaveUserRequest) (*protogen.SaveUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", arg0, arg1)
	ret0, _ := ret[0].(*protogen.SaveUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockCacheServiceServerMockRecorder) SaveUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockCacheServiceServer)(nil).SaveUser), arg0, arg1)
}

// UpdateTweet mocks base method.
func (m *MockCacheServiceServer) UpdateTweet(arg0 context.Context, arg1 *protogen.UpdateTweetRequest) (*protogen.UpdateTweetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTweet", arg0, arg1)
	ret0, _ := ret[0].(*protogen.UpdateTweetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTweet indicates an expected call of UpdateTweet.
func (mr *MockCacheServiceServerMockRecorder) UpdateTweet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTweet", reflect.TypeOf((*MockCacheServiceServer)(nil).UpdateTweet), arg0, arg1)
}

// mustEmbedUnimplementedCacheServiceServer mocks base method.
func (m *MockCacheServiceServer) mustEmbedUnimplementedCacheServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCacheServiceServer")
}

// mustEmbedUnimplementedCacheServiceServer indicates an expected call of mustEmbedUnimplementedCacheServiceServer.
func (mr *MockCacheServiceServerMockRecorder) mustEmbedUnimplementedCacheServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCacheServiceServer", reflect.TypeOf((*MockCacheServiceServer)(nil).mustEmbedUnimplementedCacheServiceServer))
}

// MockUnsafeCacheServiceServer is a mock of UnsafeCacheServiceServer interface.
type MockUnsafeCacheServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeCacheServiceServerMockRecorder
}

// MockUnsafeCacheServiceServerMockRecorder is the mock recorder for MockUnsafeCacheServiceServer.
type MockUnsafeCacheServiceServerMockRecorder struct {
	mock *MockUnsafeCacheServiceServer
}

// NewMockUnsafeCacheServiceServer creates a new mock instance.
func NewMockUnsafeCacheServiceServer(ctrl *gomock.Controller) *MockUnsafeCacheServiceServer {
	mock := &MockUnsafeCacheServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeCacheServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeCacheServiceServer) EXPECT() *MockUnsafeCacheServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedCacheServiceServer mocks base method.
func (m *MockUnsafeCacheServiceServer) mustEmbedUnimplementedCacheServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCacheServiceServer")
}

// mustEmbedUnimplementedCacheServiceServer indicates an expected call of mustEmbedUnimplementedCacheServiceServer.
func (mr *MockUnsafeCacheServiceServerMockRecorder) mustEmbedUnimplementedCacheServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCacheServiceServer", reflect.TypeOf((*MockUnsafeCacheServiceServer)(nil).mustEmbedUnimplementedCacheServiceServer))
}
