// Code generated by mockery v2.43.2. DO NOT EDIT.

package proto_mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeCacheServiceServer is an autogenerated mock type for the UnsafeCacheServiceServer type
type UnsafeCacheServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedCacheServiceServer provides a mock function with given fields:
func (_m *UnsafeCacheServiceServer) mustEmbedUnimplementedCacheServiceServer() {
	_m.Called()
}

// NewUnsafeCacheServiceServer creates a new instance of UnsafeCacheServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeCacheServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeCacheServiceServer {
	mock := &UnsafeCacheServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
